# Generated by Django 5.1.5 on 2025-01-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_category_options_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at']},
        ),
    ]
