# Generated by Django 5.1.5 on 2025-01-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(help_text='The name of the budget', max_length=100, null=True),
        ),
    ]
